export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE"

export const FETCH_TASK_REQUEST = "FETCH_TASK_REQUEST"
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS"
export const FETCH_TASK_FAILURE = "FETCH_TASK_FAILURE"

export const SEARCH_REQUEST = "SEARCH_REQUEST"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_FAILURE = "SEARCH_FAILURE"

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST"
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS"
export const TASK_DELETE_FAILURE = "TASK_DELETE_FAILURE"