
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGOUT = "LOGOUT"

export const FETCH_REQUEST = "FETCH_REQUEST"
export const FETCH_SUCCESS = "FETCH_SUCCESS"
export const FETCH_FAILURE = "FETCH_FAILURE"

export const UPDATE_REQUEST = "UPDATE_REQUEST"
export const UPDATE_FAILURE = "UPDATE_FAILURE"
export const UPDATE_SUCCESS = "UPDATE_SUCCESS"

export const COVER_IMAGE_UPDATE_REQUEST= "COVER_IMAGE_UPDATE_REQUEST"
export const COVER_IMAGE_UPDATE_SUCCESS = "COVER_IMAGE_UPDATE_SUCCESS"
export const COVER_IMAGE_UPDATE_FAILURE = "COVER_IMAGE_UPDATE_FAILURE"